title: bogwonch.net
email: bogwonch@bogwonch.net
description: >
  Notes, memos, and information from someone who wonches in bogs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bogwonch.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
