#+TITLE: Spammers

I /hate/ marketers. I /loathe/ recruiters. I get a /lot/ of spam asking
me to /“join a Webinar [1]”/ or /“start a startup [2]”/: inevitably all
these emails are from recruitment companies masquerading under the guise
of friendly academic collaboration. Well guess what? I don't like
/friendly academic collaboration/. If you have an email like this from
me, it means I don't like you.

#+BEGIN_QUOTE
  Hi /person/representative/scumbag/,

  I have not agreed to receive any marketing emails from
  /company/knowledge-hub/parasitic worm/. Remove me from all mailing
  lists immediately.

  Please also note the Privacy and Electronic Communication Regulations
  2003; It is unlawful to send marketing emails or texts to individuals
  without specific consent.

  https://ico.org.uk/for-organisations/guide-to-pecr/electronic-and-telephone-marketing/electronic-mail-marketing/

  If I hear from you or your organisation again, other than to confirm
  my removal from your mailing lists, I shall report this to the ICO.

  -- Joseph.
#+END_QUOTE

My favorite response so far included:

#+BEGIN_QUOTE
  The reason I reached out is that your technical history is impressive
  - the /mysterious reference to my CV/ project you gained during your
  time in /Trumpton/ is something we're keenly interested in. With your
  background I think you would be able to build something big and really
  maximise the impact of your research.
#+END_QUOTE

Guess someones been reading my CV. Would be nice if they actually knew
what they were talking about and referenced something I'd done in the
last five years eh?

And my technical history isn't impressive FYI. It isn't bad. I've worked
on some interesting projects in my time, but it isn't impressive. I'm
quite competent, but that's about it. Stop trying to stroke my ego: if
you want my interest talk tech to me and go into lots of deep technical
details. I'm an engineer. More tech. Less platitudes.

Eurgh. Fuck these guys.

[1] What the heck is a webinar?

[2] Over my dead body.
